/**
 * Mock strategies data for testing filters and pagination
 * This file contains extended mock data with various protocols, risks, and APYs
 */

import { FormattedStrategy } from '../hooks/useStrategies';
import { PublicKey } from '@solana/web3.js';
import { TOKEN_MINTS } from './constants';

export const getMockStrategies = (): FormattedStrategy[] => {
  const baseStrategies: FormattedStrategy[] = [
    {
      id: 'mock-1',
      name: 'USDC Stable Vault',
      token: 'USDC',
      tokenMint: TOKEN_MINTS.USDC,
      apy: 8.5,
      risk: 'Low',
      tvl: '$2.4M',
      description: 'Conservative yield strategy with minimal risk focusing on stable returns',
      protocol: 'Yield-X Protocol',
      lockPeriod: '30 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-2',
      name: 'Aave USDC Supply',
      token: 'USDC',
      tokenMint: TOKEN_MINTS.USDC,
      apy: 6.2,
      risk: 'Low',
      tvl: '$15.8M',
      description: 'Earn yield by supplying USDC to Aave lending protocol',
      protocol: 'Aave',
      lockPeriod: 'Flexible',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-3',
      name: 'Compound USDC',
      token: 'USDC',
      tokenMint: TOKEN_MINTS.USDC,
      apy: 5.8,
      risk: 'Low',
      tvl: '$8.2M',
      description: 'Supply USDC to Compound protocol for steady returns',
      protocol: 'Compound',
      lockPeriod: 'Flexible',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-4',
      name: 'SOL Staking Plus',
      token: 'SOL',
      tokenMint: TOKEN_MINTS.SOL,
      apy: 12.4,
      risk: 'Medium',
      tvl: '$5.6M',
      description: 'Enhanced SOL staking with DeFi yield optimization',
      protocol: 'Yield-X Protocol',
      lockPeriod: '21 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-5',
      name: 'Lido Staked SOL',
      token: 'SOL',
      tokenMint: TOKEN_MINTS.SOL,
      apy: 9.8,
      risk: 'Medium',
      tvl: '$42.1M',
      description: 'Liquid staking for SOL with Lido protocol',
      protocol: 'Lido',
      lockPeriod: 'Flexible',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-6',
      name: 'Raydium RAY Farming',
      token: 'RAY',
      tokenMint: TOKEN_MINTS.RAY,
      apy: 24.7,
      risk: 'High',
      tvl: '$1.2M',
      description: 'High-yield farming strategy with RAY token rewards',
      protocol: 'Raydium',
      lockPeriod: '14 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-7',
      name: 'DeFi Boost Strategy',
      token: 'RAY',
      tokenMint: TOKEN_MINTS.RAY,
      apy: 28.3,
      risk: 'High',
      tvl: '$890K',
      description: 'Aggressive DeFi strategy with liquidity mining',
      protocol: 'Yield-X Protocol',
      lockPeriod: '7 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-8',
      name: 'Balanced Growth',
      token: 'USDC',
      tokenMint: TOKEN_MINTS.USDC,
      apy: 14.2,
      risk: 'Medium',
      tvl: '$3.7M',
      description: 'Balanced strategy combining lending and yield farming',
      protocol: 'Yield-X Protocol',
      lockPeriod: '60 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-9',
      name: 'Anchor Protocol',
      token: 'USDC',
      tokenMint: TOKEN_MINTS.USDC,
      apy: 19.5,
      risk: 'High',
      tvl: '$12.3M',
      description: 'High-yield lending protocol with terra ecosystem',
      protocol: 'Anchor',
      lockPeriod: '30 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-10',
      name: 'Serum DEX Liquidity',
      token: 'SOL',
      tokenMint: TOKEN_MINTS.SOL,
      apy: 16.8,
      risk: 'Medium',
      tvl: '$6.4M',
      description: 'Provide liquidity to Serum DEX for trading fees',
      protocol: 'Serum',
      lockPeriod: '14 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-11',
      name: 'Orca Whirlpool',
      token: 'SOL',
      tokenMint: TOKEN_MINTS.SOL,
      apy: 18.9,
      risk: 'Medium',
      tvl: '$4.8M',
      description: 'Concentrated liquidity provision on Orca DEX',
      protocol: 'Orca',
      lockPeriod: '21 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-12',
      name: 'Mango Markets',
      token: 'RAY',
      tokenMint: TOKEN_MINTS.RAY,
      apy: 31.2,
      risk: 'High',
      tvl: '$2.1M',
      description: 'Leveraged trading and lending on Mango Markets',
      protocol: 'Mango',
      lockPeriod: '7 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-13',
      name: 'Tulip Protocol Vault',
      token: 'USDC',
      tokenMint: TOKEN_MINTS.USDC,
      apy: 11.7,
      risk: 'Medium',
      tvl: '$7.9M',
      description: 'Automated yield farming with Tulip Protocol',
      protocol: 'Tulip',
      lockPeriod: '45 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-14',
      name: 'Jet Protocol Lending',
      token: 'SOL',
      tokenMint: TOKEN_MINTS.SOL,
      apy: 13.6,
      risk: 'Medium',
      tvl: '$5.2M',
      description: 'Decentralized lending protocol on Solana',
      protocol: 'Jet',
      lockPeriod: '30 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-15',
      name: 'Francium Vault',
      token: 'RAY',
      tokenMint: TOKEN_MINTS.RAY,
      apy: 26.4,
      risk: 'High',
      tvl: '$1.8M',
      description: 'Leveraged yield farming with Francium protocol',
      protocol: 'Francium',
      lockPeriod: '14 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-16',
      name: 'Quarry Mining',
      token: 'SOL',
      tokenMint: TOKEN_MINTS.SOL,
      apy: 15.3,
      risk: 'Medium',
      tvl: '$3.6M',
      description: 'Liquidity mining rewards through Quarry protocol',
      protocol: 'Quarry',
      lockPeriod: '28 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-17',
      name: 'Solend Protocol',
      token: 'USDC',
      tokenMint: TOKEN_MINTS.USDC,
      apy: 7.4,
      risk: 'Low',
      tvl: '$18.7M',
      description: 'Decentralized lending on Solana blockchain',
      protocol: 'Solend',
      lockPeriod: 'Flexible',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-18',
      name: 'Apricot Finance',
      token: 'RAY',
      tokenMint: TOKEN_MINTS.RAY,
      apy: 22.8,
      risk: 'High',
      tvl: '$2.7M',
      description: 'Cross-margin lending and leveraged trading',
      protocol: 'Apricot',
      lockPeriod: '21 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-19',
      name: 'Crema Finance LP',
      token: 'SOL',
      tokenMint: TOKEN_MINTS.SOL,
      apy: 17.2,
      risk: 'Medium',
      tvl: '$4.3M',
      description: 'Concentrated liquidity AMM on Solana',
      protocol: 'Crema',
      lockPeriod: '35 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-20',
      name: 'Friktion Volt',
      token: 'SOL',
      tokenMint: TOKEN_MINTS.SOL,
      apy: 20.1,
      risk: 'High',
      tvl: '$6.8M',
      description: 'Automated options strategies for enhanced yield',
      protocol: 'Friktion',
      lockPeriod: '7 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-21',
      name: 'Mercurial Stable',
      token: 'USDC',
      tokenMint: TOKEN_MINTS.USDC,
      apy: 9.3,
      risk: 'Low',
      tvl: '$11.2M',
      description: 'Stable coin pools with minimal impermanent loss',
      protocol: 'Mercurial',
      lockPeriod: '30 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-22',
      name: 'Drift Protocol',
      token: 'RAY',
      tokenMint: TOKEN_MINTS.RAY,
      apy: 33.7,
      risk: 'High',
      tvl: '$1.5M',
      description: 'Decentralized perpetual futures trading',
      protocol: 'Drift',
      lockPeriod: '14 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-23',
      name: 'Parrot Protocol',
      token: 'SOL',
      tokenMint: TOKEN_MINTS.SOL,
      apy: 14.8,
      risk: 'Medium',
      tvl: '$5.9M',
      description: 'Synthetic asset protocol with DeFi integration',
      protocol: 'Parrot',
      lockPeriod: '42 days',
      publicKey: PublicKey.default
    },
    {
      id: 'mock-24',
      name: 'Lifinity AMM',
      token: 'USDC',
      tokenMint: TOKEN_MINTS.USDC,
      apy: 12.9,
      risk: 'Medium',
      tvl: '$8.6M',
      description: 'Proactive market making with reduced IL',
      protocol: 'Lifinity',
      lockPeriod: '21 days',
      publicKey: PublicKey.default
    }
  ];

  return baseStrategies;
};
